from apprentice import *
from apprentice.rationalapproximation   import RationalApproximation
from apprentice.polynomialapproximation import PolynomialApproximation
from apprentice.rationalapproximationSIP import RationalApproximationSIP
from apprentice.tools import readData, readApprentice
